ParseXS: fix, test 'OUTPUT foo not a param' err
If a var is listed in an OUTPUT section, but is not actually a
parameter, then the parser outputs an error message:

    Error: OUTPUT foo not a parameter

This commit:

- Fixes a typo in the error message: it was previously "not an parameter".

- Extends the warning to include RETVAL where the XSUB is void.
  Previously, it would plough on, and then give an error that it
  couldn't find 'void' in the typemap, which is less obvious what the
  problem is.

- Adds tests - this warning previously had no tests for it.